[control_plane]
98.80.207.93 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/k8s-pipeline

[workers]
44.197.246.139 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/k8s-pipeline
44.203.225.0 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/k8s-pipeline

[all:vars]
ansible_python_interpreter=/usr/bin/python3
