apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backstage
  name: backstage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backstage
  strategy: {}
  template:
    metadata:
      labels:
        app: backstage
    spec:
      containers:
      - image: dennismuturi8/backstage:dc8dfc16c770c6fd019b40276c5b203408bf84da
        name: backstage
        ports:
        - containerPort: 7007
  
