apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backstage
  name: backstage
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backstage
  strategy: {}
  template:
    metadata:
      labels:
        app: backstage
    spec:
      containers:
      - image: dennismuturi8/backstage:latest
        name: backstage
        ports:
        - containerPort: 7007
        resources: {}
status: {}
